services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_ROOT_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - /Rocketseat One/Python/MYSQL:/var/lib/mysql